apiVersion: apps/v1
kind: Deployment
metadata:
  name: verification-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: verification
  template:
    metadata:
      labels:
        app: verification
    spec:
      containers:
        - name: verification
          image: harkirath1511/verification:latest
          ports:
            - containerPort: 8081
         
